
uint64 timestamp          # time since system start (microseconds)

string flight_mode        # flight mode to set

---

bool success               # true if successful, false if error
string message             # error message if success is false

# TOPICS offboard/flight_mode 
