//
// Prerelease License - for engineering feedback and testing purposes
// only. Not for sale.
// File: attd_fun.cpp
//
// MATLAB Coder version            : 26.1
// C/C++ source code generated on  : 02-Feb-2026 16:07:18
//

// Include Files
#include "attd_fun.h"
#include "rt_nonfinite.h"
#include <cmath>

// Function Declarations
static double rt_powd_snf(double u0, double u1);

// Function Definitions
//
// Arguments    : double u0
//                double u1
// Return Type  : double
//
static double rt_powd_snf(double u0, double u1)
{
  double y;
  if (std::isnan(u0) || std::isnan(u1)) {
    y = rtNaN;
  } else {
    double d;
    y = std::abs(u0);
    d = std::abs(u1);
    if (std::isinf(u1)) {
      if (y == 1.0) {
        y = 1.0;
      } else if (y > 1.0) {
        if (u1 > 0.0) {
          y = rtInf;
        } else {
          y = 0.0;
        }
      } else if (u1 > 0.0) {
        y = 0.0;
      } else {
        y = rtInf;
      }
    } else if (d == 0.0) {
      y = 1.0;
    } else if (d == 1.0) {
      if (u1 > 0.0) {
        y = u0;
      } else {
        y = 1.0 / u0;
      }
    } else if (u1 == 2.0) {
      y = u0 * u0;
    } else if ((u1 == 0.5) && (u0 >= 0.0)) {
      y = std::sqrt(u0);
    } else if ((u0 < 0.0) && (u1 > std::floor(u1))) {
      y = rtNaN;
    } else {
      y = std::pow(u0, u1);
    }
  }
  return y;
}

//
// ATTD_FUN
//     OUT1 =
//     ATTD_FUN(PHI_DDOT,PHI_DOT,PHI_V,EY_DDDOT,EY_DDOT,EY_DOT,EY,EY_INT_V,EZ_DDDOT,EZ_DDOT,EZ_DOT,EZ,EZ_INT_V,DDYD_DDOT,DDYD_DOT,DDYD_V,DDZD_DDOT,DDZD_DOT,DDZD_V,M,U1,KPY,KPZ,KDY,KDZ,KIY,KIZ)
//
// Arguments    : double phi_ddot
//                double phi_dot
//                double phi_v
//                double ey_dddot
//                double ey_ddot
//                double ey_dot
//                double ey
//                double ey_int_v
//                double ez_dddot
//                double ez_ddot
//                double ez_dot
//                double ez
//                double ez_int_v
//                double ddyd_ddot
//                double ddyd_dot
//                double ddyd_v
//                double ddzd_ddot
//                double ddzd_dot
//                double ddzd_v
//                double m
//                double u1
//                double kpy
//                double kpz
//                double kdy
//                double kdz
//                double kiy
//                double kiz
//                double out1[6]
// Return Type  : void
//
void attd_fun(double phi_ddot, double phi_dot, double phi_v, double ey_dddot,
              double ey_ddot, double ey_dot, double ey, double ey_int_v,
              double ez_dddot, double ez_ddot, double ez_dot, double ez,
              double ez_int_v, double ddyd_ddot, double ddyd_dot, double ddyd_v,
              double ddzd_ddot, double ddzd_dot, double ddzd_v, double m,
              double u1, double kpy, double kpz, double kdy, double kdz,
              double kiy, double kiz, double out1[6])
{
  double b_t144_tmp;
  double c_t144_tmp;
  double d_t144_tmp;
  double e_t144_tmp;
  double f_t144_tmp;
  double t10;
  double t11;
  double t12;
  double t123;
  double t126;
  double t128;
  double t129;
  double t130;
  double t135;
  double t136;
  double t137;
  double t138;
  double t14;
  double t140;
  double t142;
  double t144_tmp;
  double t146;
  double t15;
  double t16;
  double t18;
  double t19;
  double t2;
  double t22;
  double t23;
  double t24;
  double t25;
  double t27;
  double t27_tmp;
  double t28;
  double t28_tmp;
  double t29;
  double t3;
  double t31;
  double t32;
  double t33;
  double t34;
  double t34_tmp;
  double t35;
  double t40;
  double t41;
  double t43;
  double t44;
  double t45;
  double t47;
  double t48;
  double t49;
  double t50;
  double t51;
  double t53;
  double t54;
  double t6;
  double t9;
  //     This function was generated by the Symbolic Math Toolbox version 26.1.
  //     30-Jan-2026 21:41:15
  t2 = std::cos(phi_v);
  t3 = std::sin(phi_v);
  t6 = phi_dot * phi_dot;
  t19 = 1.0 / u1;
  t9 = ddyd_v * t2;
  t10 = ddyd_dot * t2;
  t11 = ddzd_v * t2;
  t12 = ddzd_dot * t2;
  t14 = ddyd_v * t3;
  t15 = ddyd_dot * t3;
  t16 = ddzd_v * t3;
  t18 = ddzd_dot * t3;
  t130 = ey_dot * kdy;
  t22 = t130 * t2;
  t54 = ey_ddot * kdy;
  t23 = t54 * t2;
  t48 = ez_dot * kdz;
  t24 = t48 * t2;
  t44 = ez_ddot * kdz;
  t25 = t44 * t2;
  t27_tmp = ey * kiy;
  t27 = t27_tmp * t2;
  t28_tmp = ey_int_v * kiy;
  t28 = t28_tmp * t2;
  t135 = ez * kiz;
  t29 = t135 * t2;
  t140 = ez_int_v * kiz;
  t31 = t140 * t2;
  t136 = ey * kpy;
  t32 = t136 * t2;
  t142 = ey_dot * kpy;
  t33 = t142 * t2;
  t34_tmp = ez * kpz;
  t34 = t34_tmp * t2;
  t146 = ez_dot * kpz;
  t35 = t146 * t2;
  t40 = t130 * t3;
  t41 = t54 * t3;
  t43 = t48 * t3;
  t44 *= t3;
  t45 = t27_tmp * t3;
  t47 = t28_tmp * t3;
  t48 = t135 * t3;
  t49 = t140 * t3;
  t50 = t136 * t3;
  t51 = t142 * t3;
  t53 = t34_tmp * t3;
  t54 = t146 * t3;
  t123 = 1.0 / (t2 * t2 + t3 * t3);
  t126 = ((((((t22 + t28) + t32) + t43) + t49) + t53) - t9) - t16;
  t128 = ((((((t11 + t40) + t47) + t50) - t14) - t24) - t31) - t34;
  t129 = t128 * t128;
  t137 =
      ((((((((((((((t12 + t41) + t45) + t51) + phi_dot * t22) + phi_dot * t28) +
               phi_dot * t32) +
              phi_dot * t43) +
             phi_dot * t49) +
            phi_dot * t53) -
           t15) -
          t25) -
         t29) -
        t35) -
       phi_dot * t9) -
      phi_dot * t16;
  t138 = ((((((((((((((t23 + t27) + t33) + t44) + t48) + t54) + phi_dot * t14) +
                 phi_dot * t24) +
                phi_dot * t31) +
               phi_dot * t34) -
              t10) -
             t18) -
            phi_dot * t11) -
           phi_dot * t40) -
          phi_dot * t47) -
         phi_dot * t50;
  t144_tmp = ey_dddot * kdy;
  b_t144_tmp = ez_dddot * kdz;
  c_t144_tmp = ey_dot * kiy;
  d_t144_tmp = ez_dot * kiz;
  e_t144_tmp = ey_ddot * kpy;
  f_t144_tmp = ez_ddot * kpz;
  t54 = ((((((((((((((((((((((((((((((ddzd_ddot * t2 + t144_tmp * t3) +
                                     c_t144_tmp * t3) +
                                    e_t144_tmp * t3) +
                                   phi_ddot * t22) +
                                  phi_ddot * t28) +
                                 phi_ddot * t32) +
                                phi_ddot * t43) +
                               phi_ddot * t49) +
                              phi_ddot * t53) -
                             ddyd_ddot * t3) -
                            b_t144_tmp * t2) -
                           d_t144_tmp * t2) -
                          f_t144_tmp * t2) -
                         phi_ddot * t9) -
                        phi_dot * t10 * 2.0) -
                       phi_ddot * t16) -
                      phi_dot * t18 * 2.0) +
                     phi_dot * t23 * 2.0) +
                    phi_dot * t27 * 2.0) +
                   phi_dot * t33 * 2.0) +
                  t6 * t14) +
                 phi_dot * t44 * 2.0) +
                phi_dot * t48 * 2.0) +
               phi_dot * t54 * 2.0) +
              t6 * t24) +
             t6 * t31) +
            t6 * t34) -
           t6 * t11) -
          t6 * t40) -
         t6 * t47) -
        t6 * t50;
  t48 = m * m * (t19 * t19) * (t123 * t123);
  t130 = t48 * t129;
  t10 = t137 * t137;
  t18 = 1.0 / (t130 - 1.0);
  t135 = 1.0 / std::sqrt(-t130 + 1.0);
  t140 = t48 * (t126 * t126) * t18;
  t136 = rt_powd_snf(t135, 3.0);
  t142 = 1.0 / std::sqrt(t140 + 1.0);
  t44 = m * t19 * t123;
  t27_tmp =
      rt_powd_snf(m, 3.0) * rt_powd_snf(t19, 3.0) * rt_powd_snf(t123, 3.0);
  t130 = t27_tmp * t126;
  t34_tmp = t130 * t128 * t136;
  t146 = t44 * t135 * t138 + t34_tmp * t137;
  out1[0] = -std::asin(t44 * t128);
  out1[1] = -std::asin(t44 * t126 * t135);
  t28_tmp = -m * t19 * t123 * t135;
  out1[2] = t28_tmp * t137;
  out1[3] = -t142 * t146;
  t44 = t27_tmp * t128 * t136;
  out1[4] = t28_tmp * t54 - t44 * t10;
  out1[5] =
      -t142 * ((((t28_tmp * (((((((((((((((((((((((((((((((ddyd_ddot * t2 +
                                                           ddzd_ddot * t3) +
                                                          phi_dot * t12 * 2.0) -
                                                         phi_dot * t15 * 2.0) -
                                                        phi_dot * t25 * 2.0) -
                                                       phi_dot * t29 * 2.0) -
                                                      phi_dot * t35 * 2.0) +
                                                     phi_dot * t41 * 2.0) +
                                                    phi_dot * t45 * 2.0) +
                                                   phi_dot * t51 * 2.0) +
                                                  phi_ddot * t11) +
                                                 phi_ddot * t40) +
                                                phi_ddot * t47) +
                                               phi_ddot * t50) +
                                              phi_ddot * -t14) +
                                             phi_ddot * -t24) +
                                            phi_ddot * -t31) +
                                           phi_ddot * -t34) +
                                          t6 * t22) +
                                         t6 * t28) +
                                        t6 * t32) +
                                       t6 * t43) +
                                      t6 * t49) +
                                     t6 * t53) +
                                    t6 * -t9) +
                                   t6 * -t16) -
                                  t144_tmp * t2) -
                                 b_t144_tmp * t3) -
                                c_t144_tmp * t2) -
                               d_t144_tmp * t3) -
                              e_t144_tmp * t2) -
                             f_t144_tmp * t3) +
                  t130 * t136 * t10) +
                 rt_powd_snf(m, 5.0) * rt_powd_snf(t19, 5.0) *
                     rt_powd_snf(t123, 5.0) * t126 * t129 *
                     rt_powd_snf(t135, 5.0) * t10 * 3.0) +
                t34_tmp * t54) +
               t44 * t137 * t138 * 2.0) +
      rt_powd_snf(t142, 3.0) * t146 *
          (t48 * t126 * t18 * t138 * 2.0 -
           t48 * t128 * t18 * t137 * t140 * 2.0) /
          2.0;
}

//
// File trailer for attd_fun.cpp
//
// [EOF]
//
